### ISSUE TITLE
Script crashes upon exporting project

### ISSUE THREAD

**Issue by MaddyGuthridge** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#29]
```
Traceback (most recent call last):
  File "<string>", line 131, in OnInit
  File "<string>", line 59, in OnInit
  File "D:\migue\Documents\Image-Line\FL Studio\Settings\Hardware\Novation-LaunchKey-Mk2\lighting.py", line 229, in lightShow
  File "D:\migue\Documents\Image-Line\FL Studio\Settings\Hardware\Novation-LaunchKey-Mk2\lighting.py", line 144, in reset
  File "D:\migue\Documents\Image-Line\FL Studio\Settings\Hardware\Novation-LaunchKey-Mk2\internal.py", line 555, in sendMidiMessage
  File "D:\migue\Documents\Image-Line\FL Studio\Settings\Hardware\Novation-LaunchKey-Mk2\internal.py", line 569, in sendCompleteMidiMessage
TypeError: Linked device not assigned
```

Possibly to do with linked device not being ready yet?
Check with FL Studio team.

**Comment by MaddyGuthridge** [comment]
Fixed as of FL Studio v20.8.0
